---
title: "HEV_dataset"
author: "Jaske"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
library(forcats)
library(lubridate)
```
```{r}
hev <- read.csv2("~/1st_Master_BI/BUSIN/Project/HEV_article_2018_filtered.csv")
View(hev)
```

```{r}
str(hev)
```

```{r}
hev <- hev %>% select(-Car_sharing_)

hev1 <- hev %>% mutate(Gender = as.factor(Gender),
                       Education_level = as.factor(Education_level),
                       Employment_status = as.factor(Employment_status),
                       Income_group = as.factor(Income_group),
                       Country = as.factor(Country),
                       buy_electric = as.logical(buy_electric),
                       Household_members_number = as.factor(Household_members_number),
                       Plan_to_purchase_vehicle = as.factor(Plan_to_purchase_vehicle))

```

```{r}
levels(hev1$Gender) <- c("M", "F")

levels(hev1$Country) <- c("Austria", "Belgium", "Bulgaria", "Croatia", "Czech Republic",
                          "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
                          "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Netherlands",
                          "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain",
                          "Sweden", "Great Britain", "Malta", "Luxembourg", "Cyprus")

levels(hev1$Education_level) <- c("Primary (elementary school)", 
                                  "Lower secondary (upper elementary school)", 
                                  "Upper secondary (high school)", 
                                  "Tertiary and higher (University degree or PhD)")

levels(hev1$Employment_status) <- c("Full time employed", "Part time employed", "Unemployed",
                                    "Studying", "Retired", "Other", "I prefer not to answer")

levels(hev1$Household_members_number) <- c("one (myself)", "two", "three", "four", "five", 
                                           "more than five", "I prefer not to answer")

levels(hev1$Plan_to_purchase_vehicle) <- c("Yes, in the next 6 months",
                                           "Yes, in the next 12 months",
                                           "Yes, in the next 2 years", "No", 
                                           "Don’t know/no answer")

levels(hev1$Income_group) <- c("high", "higher middle", "middle", "lower middle", "low", 
                               "I prefer not to answer")

```

```{r}
hev1 %>% summary()
```

```{r}
hev1 %>% ggplot(aes(Age)) + geom_bar(aes(fill = buy_electric), position = "fill")
```

```{r}
hev1 %>% ggplot(aes(Gender)) + geom_bar(aes(fill = buy_electric), position = "dodge")
```

```{r}
hev1 %>% ggplot(aes(Income_group)) + geom_bar(aes(fill = buy_electric), position = "dodge")
```
```{r}
hev1 %>% group_by(Country, Gender, buy_electric) %>% summarise(n = n(), median(Age)) %>% arrange(desc(n))
```

```{r}
levels(hev1$Income_group)
```

