in---
title: "Superchargers map"
author: "Caro Haesen"
date: "26-10-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(maps)
library(ggplot2)
library(tidyr)
library(dplyr)
library(lubridate)
library(ggmap)
library(mapdata)
library(mapproj)
library(sf)
library(rnaturalearth)
library(hrbrthemes)
library(grid)
library(rworldmap)
library(shiny)
library(plotly)

```
```{r}
superchargers <- read_xlsx("Data/Superchargers.xlsx")
summary(superchargers)
superchargers <- superchargers %>% separate(GPS, sep = ",", into = c("Latitude", "Longitude"))
superchargers$Longitude <- as.double(superchargers$Longitude)
superchargers$Latitude <- as.double(superchargers$Latitude)
superchargers <- data.frame(superchargers)
```

```{r}
world_data <- ggplot2::map_data('world')
world_data <- fortify(world_data)
head(world_data)
```

```{r}
# Some EU Contries
some.eu.countries <- c("Norway", "Sweden", "Finland", "Denmark", "UK","Ireland", "Greece",
                "Belgium", "Netherlands", "France", "Spain", "Portugal", "Luxembourg", "Croatia",
                "Germany", "Switzerland", "Austria", "Slovenia", "Italy", "Bulgaria", "Romania",
                "Czech Rep.", "Slovakia", "Hungary", "Poland", "Bosnia Hercegovina", "Serbia",
                "Turkey", "Ukraine", "Moldova", "Belarus", "Estonia", "Latvia", "Lithuania",
                "Montenegro", "Albania", "Macedonia", "Iceland")
# Retrievethe map data
some.eu.maps <- map_data("world", region = some.eu.countries)

# Compute the centroid as the mean longitude and lattitude
# Used as label coordinate for country's names
region.lab.data <- some.eu.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))

europe <- ggplot(some.eu.maps, aes(x = long, y = lat)) + geom_polygon(aes( group = group), color='black', fill = 'white')+
  geom_text(aes(label = region), data = region.lab.data,  size = 2, hjust = 0.5)+
  scale_fill_viridis_d()+
  theme_void()+
  theme(legend.position = "none") + coord_fixed(1.3)
print(europe)
```

```{r}
europe + geom_point(data = superchargers, aes(x = Longitude, y = Latitude), size = 0.3, color = 'red') + coord_fixed(1.3)
```

```{r}
getEuropePlot <- function(){

  ## Get the world map: ##
  worldMap <- getMap()
  
  ## Define vector with all European countries: ##
  v.europe <- c("Norway", "Sweden", "Finland", "Denmark", "United Kingdom","Ireland", "Greece",
                "Belgium", "Netherlands", "France", "Spain", "Portugal", "Luxembourg", "Croatia",
                "Germany", "Switzerland", "Austria", "Slovenia", "Italy", "Bulgaria", "Romania",
                "Czech Rep.", "Slovakia", "Hungary", "Poland", "Bosnia Hercegovina", "Serbia",
                "Turkey", "Ukraine", "Moldova", "Belarus", "Estonia", "Latvia", "Lithuania",
                "Montenegro", "Albania", "Macedonia")
  
  ## Select only the index of countries of Europe: ##
  indEU <- which(worldMap$NAME%in%v.europe)
  
  
  ## Extract longitude and latitude border's coordinates of countries: ##
  df.europeCoords <- lapply(indEU, function(i){
    df <- data.frame(worldMap@polygons[[i]]@Polygons[[1]]@coords)
    df$region = as.character(worldMap$NAME[i])
    colnames(df) <- list("long", "lat", "region")
    return(df)
  })
  df.europeCoords <- do.call("rbind", df.europeCoords)
  names(df.europeCoords) <- c("longitude", "latitude", "country")
  
  ## Deletes/Removes borders of PLOT: ##
  ax <- list(
    title = "",
    zeroline = FALSE,
    showline = FALSE,
    showticklabels = FALSE,
    showgrid = FALSE
  )
  
  ## Plot the map: ##
  p <- ggplot(data = df.europeCoords, aes(x = longitude, y = latitude, group = country, 
                                          text = paste("<b>", country, '</b>\n')), 
              color = "grey50", size = 0.1) + 
    geom_polygon() +
    coord_map(xlim = c(-13, 35),  ylim = c(32, 71)) +
    theme_classic() +
    theme(axis.text.x = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(), axis.title = element_blank(), legend.position = "none",
          plot.margin = unit(0 * c(-1.5, -1.5, -1.5, -1.5), "lines")) 
  
  ## Create plot_ly() object: ##
EuropePlot <- plotly::ggplotly(p, tooltip = "text") %>%
    layout(xaxis = ax, yaxis = ax) 
   
}


#ui <- fluidPage(
  #plotlyOutput (outputId = "maPPInfoPLOT", width = "900px", height = "600px"))

#server <- function(input, output, session) {
  # PLOT-Output: #
 # EuropePlot <- getEuropePlot()
 # output$maPPInfoPLOT <- renderPlotly({
    #plotly::ggplotly(EuropePlot, dynamicTicks = TRUE)})}

#shinyApp(ui, server)
```

