---
title: "Uitbreiding EU per land infrastructure"
author: "Lien"
date: "30 oktober 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyr)

countriesafinfrastructure <- read_xlsx("countries overview of af infrastructure.xlsx", skip = 2 , col_types = c("text", "text", "numeric", "numeric", "numeric", "numeric", "numeric"))
summary(countriesafinfrastructure)
```


```{r}
countriesafinfrastructure <- countriesafinfrastructure %>% gather('Electricity', 'H2', 'Natural Gas', 'LPG', 'Total', key = 'brandstof', value = 'waardes')
```


```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2008') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF infrastructure 2008', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000000, by= 100000)) + theme(axis.text.x = element_text(angle = 45))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2009') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2009', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000000, by= 100000)) + theme(axis.text.x = element_text(angle = 45))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2010') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2010', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000, by= 100)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2011') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2011', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,2000, by= 200)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2012') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2012', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 200)) + theme(axis.text.x = element_text(angle = 90))

```


```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2013') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2013', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 500)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2014') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2014', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,20000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2015') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2015', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2016') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2016', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 2000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2017') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2017', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2018') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2018', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2019') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2019', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Year == '2020') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2020', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```


Brandstof is Electricity
```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2010') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2010', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000, by= 100)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2011') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2011', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,2000, by= 200)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2012') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2012', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 200)) + theme(axis.text.x = element_text(angle = 90))

```


```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2013') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2013', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 500)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2014') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2014', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,20000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2015') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2015', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2016') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2016', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 2000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2017') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2017', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2018') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2018', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2019') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2019', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafinfrastructure %>% filter(brandstof == 'Electricity', Year == '2020') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack")  + labs(title = 'Countries overview of AF infrastructure 2020', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 5000)) + theme(axis.text.x = element_text(angle = 90))

```


Belgium over the years
```{r}

countriesafinfrastructure %>% filter(brandstof != 'Total', Country == 'BE') %>% ggplot(aes(x = Year, y = waardes, fill = brandstof))+ geom_col(position = "dodge")  + labs(title = 'Countries overview of AF infrastructure BE', subtitle = 'Total number of AF infrastructure per type of fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```
