---
title: "Uitbreiding EU per land paggenger cars"
author: "Lien"
date: "31 oktober 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyr)

countriesafpassengercars <- read_xlsx("Data/Countries overview of af passenger cars.xlsx", skip = 2 , col_types = c("text", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
summary(countriesafpassengercars)
```


```{r}
countriesafpassengercarsev <- countriesafpassengercars %>% mutate('EV' = BEV + PHEV)
countriesafpassengercars <- countriesafpassengercars %>% gather('BEV', 'H2', 'CNG', 'LNG', 'PHEV', 'LPG', 'Total', key = 'brandstof', value = 'waardes')
```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2008') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2008', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2008') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2008', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2009') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2009', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2009') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2009', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2010') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2010', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2010') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2010', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2011') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2011', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2011') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2011', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2012') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2012', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2012') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2012', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000, by= 1000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2013') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2013', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```
Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2013') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2013', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2014') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2014', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2014') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2014', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```


```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2015') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2015', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2015') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2015', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2016') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2016', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2016') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2016', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2017') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2017', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2017') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2017', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2018') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2018', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2018') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2018', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2019') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2019', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2019') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2019', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Year == '2020') %>% ggplot(aes(x = Country, y = waardes, fill = brandstof))+ geom_col(position = "stack") + labs(title = 'Countries overview of AF passenger cars 2020', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,10000000, by= 1000000)) + theme(axis.text.x = element_text(angle = 90))

```
Electrisch
```{r}

countriesafpassengercarsev %>% filter(Year == '2020') %>% ggplot(aes(x = Country, y = EV))+ geom_col() + labs(title = 'Countries overview of AF passenger cars 2020', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,1000000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

Belgium over the years
```{r}

countriesafpassengercars %>% filter(brandstof != 'Total', Country == 'BE') %>% ggplot(aes(x = Year, y = waardes, group = brandstof, color = brandstof))+ geom_line()  + labs(title = 'Overview of AF passenger cars BE', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

Electrisch
```{r}

countriesafpassengercarsev %>% filter(Country == 'BE') %>% ggplot(aes(x = Year, y = EV))+ geom_col() + labs(title = 'Overview of AF passenger cars BE electric', subtitle = 'Total fleet of passenger cars per alternative fuel', y = '')  + scale_y_continuous(breaks = seq(0,100000, by= 10000)) + theme(axis.text.x = element_text(angle = 90))

```

